### ISSUE TITLE
runscript(script.skinvariables) triggering skin reload

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/script.skinvariables#2]
Thanks for yet another great addon! 

I am doing a test run and everything appears to be working as expected, the includes file is being created with all the correct variables.

I added runscript(script.skinvariables) as an onload to Home.xml, however it appears that this is causing a skin reload every time Home is loaded, even without having made any changes to the json file.

Have I missed something?

**Comment by jurialmunkey** [comment]
Hmm, it shouldn't do so. It should only rebuild and reloadskin if the json file has changed. It's possible that Kodi is maybe translating the hash number into a localized string -- can you test latest and see if it is still happening.

However, I should point out that this addon doesn't need to run on the user side of things -- just use it to generate your variables on your machine and then commit the file it generates. The generated file should be the same for every user -- there's no need to make this a dependency or anything like that.

**Comment by skyfsza** [comment]
Thanks for feedback.

Very good point, no need to have an onload just include the generated files.

Will test latest version and let you know if it fixed the onload loop none the less.

**Comment by jurialmunkey** [comment]
It can still be useful to have it as an onload just so you don't need to run it manually when you make changes.

`<onload condition="System.HasAddon(script.skinvariables)">Runscript(script.skinvariables)</onload>`

That will make sure it only runs if you have it installed (so it won't prompt users if they don't have it installed).

**Comment by skyfsza** [comment]
Just did a quick test, still getting the skin reload loops if i use the onload.

**Comment by jurialmunkey** [comment]
Ah yep you're right. Dumb mistake on my part -- I was only testing with folder arg specified and didn't test without it. Should be fixed now.

**Comment by skyfsza** [comment]
Thanks, can confirm no more loops with onload on the latest version.
