### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Hitcher** [jurialmunkey/script.skinvariables#21]
In the rules definitions table found in [Generating Expressions](https://github.com/jurialmunkey/script.skinvariables/wiki/Skin-Viewtype-Builder#generating-expressions) `plugin` should be `plugins`.

**Comment by jurialmunkey** [comment]
Thanks, should be fixed now.

**Comment by Hitcher** [comment]
Thanks, it did catch me out for a bit.
