### ISSUE TITLE
Single Variable multiple containers

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/script.skinvariables#3]
One of the first use cases I had for the script was generating variables for fanart background of the first widget whilst focused on the Home Menu ( much like you do in AZ2 Includes_Global).

I am using the following:
 {
        "name"          : "Netflix_Hub_Fanart",
        "containers"    : [6050,6051,6052,6053,6054,6055,6056,6057,6058,6059,6060,6061,6062,6063,6064,6065,6066,6067,6068],
        "listitems"     : {"start": 1, "end": 1},
        "values"        : [
                            {"!String.IsEmpty({listitem}.Art(fanart))": "$INFO[{listitem}.Art(fanart)]"},
                            {"!String.IsEmpty({listitem}.Art(tvshow.fanart))": "$INFO[{listitem}.Art(tvshow.fanart)]"}
                          ]
    }

This results in 
$VAR[Netflix_Hub_Fanart_C6050]
$VAR[Netflix_Hub_Fanart_C6051]
$VAR[Netflix_Hub_Fanart_C6052]
etc 

Is it possible to allow for an argument where instead of individual variables for each container the script generates a single variable with all the containers inside? 

Currently i'm doing the following, which to a degree feels like it goes against the purpose of the script:
`  <variable name="Netflix_Hub_Fanart_Group">
        <value condition="Control.IsVisible(6050)">$VAR[Netflix_Hub_Fanart_C6050]</value>
        <value condition="Control.IsVisible(6051)">$VAR[Netflix_Hub_Fanart_C6051]</value>
        <value condition="Control.IsVisible(6052)">$VAR[Netflix_Hub_Fanart_C6052]</value>
        <value condition="Control.IsVisible(6053)">$VAR[Netflix_Hub_Fanart_C6053]</value>
        <value condition="Control.IsVisible(6054)">$VAR[Netflix_Hub_Fanart_C6054]</value>
 </variable>`

Also, for values, is it possible for you to add {container}  so i can add Control.IsVisible({container}) to the json?

Thanks!

**Comment by jurialmunkey** [comment]
Ah good ideas

With latest you can now also use `{id}` for the container ID and `{position}` for the listitem position.

You can also specify a "parent" condition like so

```json
{
    "name"          : "Netflix_Hub_Fanart",
    "containers"    : [6050,6051,6052,6053,6054,6055,6056,6057,6058,6059,6060,6061,6062,6063,6064,6065,6066,6067,6068],
    "listitems"     : {"start": 1, "end": 1},
    "parent"        : "Control.IsVisible({id})",
    "values"        : [
                        {"!String.IsEmpty({listitem}.Art(fanart))": "$INFO[{listitem}.Art(fanart)]"},
                        {"!String.IsEmpty({listitem}.Art(tvshow.fanart))": "$INFO[{listitem}.Art(tvshow.fanart)]"}
                      ]
}
```

This parent condition will build `$VAR[Netflix_Hub_Fanart_Parent]` with the string specified as the condition for each variable. The last condition will be the fallback to the variable without a container specified -- e.g.
```xml
<variable name="Netflix_Hub_Fanart_Parent">
    <value condition="Control.IsVisible(6050)">$VAR[Netflix_Hub_Fanart_C6050]</value>
    <value condition="Control.IsVisible(6051)">$VAR[Netflix_Hub_Fanart_C6051]</value>
    <value condition="Control.IsVisible(6052)">$VAR[Netflix_Hub_Fanart_C6052]</value>
    [...etc...]
    <value condition="True">$VAR[Netflix_Hub_Fanart]</value>
</variable>

**Comment by skyfsza** [comment]
Brilliant thank you!

Just did a quick test and its working perfectly.
