### ISSUE TITLE
Adding null_id to an already generated template results in a malformed file.

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/script.skinvariables#36]
Create a template without null_id:-

```
<includes>
    <variable name="Test" containers="9000" parent="Control.Hasfocus({id})">
        <value>$INFO[{listitem}.ListItem.Label]</value>
    </variable>
</includes>
```

`RunScript(script.skinvariables,action=buildvariables,template=test)`

Then edit the template to add null_id and generate again:-

```
<includes>
    <variable name="Test" containers="9000" null_id="true" parent="Control.Hasfocus({id})">
        <value>$INFO[{listitem}.ListItem.Label]</value>
    </variable>
</includes>
```

`RunScript(script.skinvariables,action=buildvariables,template=test)`

Results in the generated file being malformed:-

![Untitled1](https://github.com/jurialmunkey/script.skinvariables/assets/4118048/5ad436c9-64d6-4cc8-b602-b7a1e39e590c)

A minor bug fixed by making sure you delete the original generated file before regenerating it, but a bug none the less.

**Comment by jurialmunkey** [comment]
Sorry when you say malformed what are you referring to? The nul character at the end?

Or are you just saying it doesn't build? 

Because if the latter, the check for the file change is not very detailed and it probably just didn't trigger because the number of lines stayed the same in the source - but you can force by adding the "force" param to the RunScript command.

**Comment by roidy** [comment]
> Sorry when you say malformed what are you referring to? The nul character at the end?
> 
> Or are you just saying it doesn't build?

Both. The 'test_Container' variable isn't built. However a new file is clearly generated as after building it contains a string of null characters at the end.

As I said it's not a major issue, I can just delete the file and rebuild, it's just strange that it only happens when adding the 'null_id' property. I can make others changes that don't increase or decrease the line count and the file is generated fine without all the null's at the end.

**Comment by jurialmunkey** [comment]
I can't seem to reproduce. Using your exact code and steps above it correctly produces the file and updates it
BTW your `{listitem}.ListItem.Label` is why it doubles "ListItem" here. Should just be `{listitem}.Label`

![image](https://github.com/jurialmunkey/script.skinvariables/assets/4618719/2709aecf-88c8-43f8-b698-d033cb5975c6)

**Comment by roidy** [comment]
Yep, the '{listitem}.ListItem' was a typo when I posted the issue my actual code is correct.

The issue is repeatable every time for me. Here's a video:- https://streamable.com/al7za4

**Comment by jurialmunkey** [comment]
So strange. I really can't think what would cause it. 

My first thought is that your editor is adding a different line ending character but that doesn't explain why it then works if you delete the file.

If you add  `, force` to the runscript command does it still happen?

I'll have another look at the code and see if I spot anything but very strange

**Comment by roidy** [comment]
Adding `force` causes the template to generate ok, but adding `force` causes the problem of Kodi going into an infinite loop of reloading the skin.

I mainly develop on a MacBook running OSX and VSCode, I just tried to reproduce the issue on my Windows machine using the exact same version of VSCode and it works perfectly. 

All my skin files are located on an AMLogic box running CoreELEC which I connect to using an SMB share, so maybe SMB on Mac has something to do with it, but then why only when adding the `null_id` attribute.

As I said it's not a major issue I just need to remember that if I'm using `null_id` then I need to delete the old file first.
