### ISSUE TITLE
Impossible to install skinvariables on libreElec 11.0.6

### ISSUE THREAD

**Issue by moi952** [jurialmunkey/script.skinvariables#39]
Hello, 

I want to install Artic Fuse on LibreELEC 11.0.6

When i want to install theme I have a window that opens to tell me that certain extensions are going to be installed.
And when installing skin variable I got the error: "The dependency of script.skinvariables 2.1.7 could not be satisfied"

<img width="665" alt="Capture d’écran 2024-03-16 à 01 11 38" src="https://github.com/jurialmunkey/script.skinvariables/assets/52632400/12a35e00-873f-48c6-aea9-28bf3c89c0ae">
<img width="1029" alt="Capture d’écran 2024-03-16 à 01 12 36" src="https://github.com/jurialmunkey/script.skinvariables/assets/52632400/a4398b60-f7cd-4d15-894f-6d88ce3203c3">

I thank you for your work, and for your help :)

**Comment by jurialmunkey** [comment]
Follow all the instructions on the first page of the forum post for fuse.
