### ISSUE TITLE
Dialog multiselect is broken

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/script.skinvariables#51]
RunScript(script.skinvariables,run_dialog=multiselect,heading=Multiselect test,list=Item 1 / Item 2 / Item 3 / Item 4 / Item 5 / Item 6 / Item 7 / Item 8 / Item 9 / Item 10)

This opens a standard select dialog and allows you to choose only one item, not multiple.

Looking at the code: https://github.com/jurialmunkey/script.skinvariables/blob/dfdf01680e5bbd6198544ab1d135c41ba45ea6c0/resources/lib/method.py#L222-L229

func should be dialog.multiselect
('list', _split_items, '') should be ('options', _split_items, '')
('preselect', _get_preselected_items, -1) should take a tuple or list of items.... I think.

**Comment by jurialmunkey** [comment]
Resolved by #52
