### ISSUE TITLE
Question about "Randomise" setting in SkinVariables

### ISSUE THREAD

**Issue by Mahava** [jurialmunkey/script.skinvariables#53]
Hi Jurialmunkey,

I added folder paths to skinvariables one at a time then set it to 'randomise=true', then used it as a widget but only the folder paths that have a name without spaces or special characters will randomise.  Skinvariables ignores everything else.   That is, it randomised the folder paths names "War" and "History" but ignored the one named "Visually Stunning"....without quotes.

I'm trying to mimic the action of autowidgets where it takes a set of paths and cycles through them one at a time and displays as a widget.  ...and it seems to work, except that it ignores any folder that has spaces.

The other thing is that the folder paths have to be added one at a time.  I don't think it will work if I add a node from TMDB Helper, and I can't change the timing of the refresh.

**Comment by Mahava** [comment]
I did some more testing with another folder with spaces in name and it did work.  Maybe it was ignoring the other folder because of api restrictions

will delete

**Comment by Liquidrag** [comment]
@Mahava can you explain a little more on how you got it working? I can't seem to get it working.

**Comment by Mahava** [comment]
> @Mahava can you explain a little more on how you got it working? I can't seem to get it working.

Sorry, I just saw your question.

-go into Skin Variables (SV) and select 'add new'
-select what type to add, for me its usually 'Video add-on'
-navigate through the addon to the list you want to add and when you get there select 'add folder' YOU HAVE TO BE ACTUALLY -INSIDE THE FOLDER
-Next you can change the folder name or just select 'done' on the keyboard to keep original name
-SV will ask if you want to add another path.  Say 'yes' and continue as before until you have all your paths then say 'no'
-at this point SV will ask you for sort method, inclusions, exclusions etc.  Select what you want or 'none'
-Finally, give the whole thing(.json) a name
-In SV, bring up the context menu of the .json you just created and select 'edit filters'
-Inside you'll see all the paths you added etc
-click on 'randomise=false' to toggle it to true
-scroll to the bottom and select 'save'

Now when you click on the .json you created, only one path at a time will display, randomised.   Then you can add the .json you created to your skin's widgets.

**Comment by Liquidrag** [comment]
@Mahava thank you. I’ll give it a try.
