### ISSUE TITLE
Clarity on how to combine paths into one list

### ISSUE THREAD

**Issue by metaltermite** [jurialmunkey/script.skinvariables#58]
The wiki explains how to combine paths here https://github.com/jurialmunkey/script.skinvariables/wiki/Filtering-Plugin-and-Library-Directories though I cannot seem to get it to work; the results only show one path.

I have two paths, `TMDBHelper > Trakt > Recently Watched Shows` and `TMDBHelper > Trakt > Recently Watched Movies`,
1. `plugin://plugin.video.themoviedb.helper/?info=trakt_history&tmdb_type=tv&widget=true&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]`
2. `plugin://plugin.video.themoviedb.helper/?info=trakt_history&tmdb_type=movie&widget=true&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]`

According to the wiki, I would combine the above two paths as such, `1&amp;&amp;2`, into one path in the corresponding JSON file,

```json
"paths": [
        "plugin://plugin.video.themoviedb.helper/?info=trakt_history&tmdb_type=tv&widget=true&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]&amp;&amp;plugin://plugin.video.themoviedb.helper/?info=trakt_history&tmdb_type=movie&widget=true&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]"
    ],
```

However in practice this only parses the first path, so I'm clearly doing something wrong.

**Comment by jurialmunkey** [comment]
No this is not for the json file. Combined path with double ampersand is for inside a skin to Skinner use.

Multiple paths should be on separate lines in the paths list in the json.

It is simpler to just use the gui editor inside skinvariables.

**Comment by metaltermite** [comment]
> It is simpler to just use the gui editor inside skinvariables.

Alright, that makes sense. Thanks for the clarification.

The issue that caused me to veer off the GUI path persists though:

When adding multiple paths via the GUI, as in my above example -- `Your recently watched tv shows` and `Your recently watched movies` from TMDB Helper>Trakt -- the contents of both lists are not sorted by `lastplayed`, rather they're just added as two sequential lists showing all the tv shows first, followed by all the movies.

Is this this a limitation or am I doing something wrong?

**Comment by jurialmunkey** [comment]
> Is this this a limitation or am I doing something wrong?

TMDbHelper items will not have a LastPlayed value because they are not local items.

The only way they would have a LastPlayed value is if they also exist in your local library AND the local library has a lastplayed value AND you have TMDbHelper set to retrieve additional details from the Kodi DB.

Otherwise ListItem.LastPlayed is blank and so the list is sorted correctly (no sorting, so it is in the order the items were retrieved).

**Comment by jurialmunkey** [comment]
If this is a feature that is desired for TMDbHelper Trakt sync lists, I think it'd be better handled directly in TMDbHelper. 

It already has the ability to combine content for other types of Trakt lists (e.g. Random Combined Anticipated etc. or for custom user lists) so it shouldn't be a huge leap for me to add this for sync lists too (where it makes sense - obviously some data doesn't make sense to combine)

**Comment by metaltermite** [comment]
> If this is a feature that is desired for TMDbHelper Trakt sync lists, I think it'd be better handled directly in TMDbHelper.
> 
> It already has the ability to combine content for other types of Trakt lists (e.g. Random Combined Anticipated etc. or for custom user lists) so it shouldn't be a huge leap for me to add this for sync lists too (where it makes sense - obviously some data doesn't make sense to combine)

Thanks for taking the time to explain why it wasn't working.

I've been using all your skins for years now, and I've grown to notice that it would be a lot more efficient from a ui/ux pov to sometimes browse particular lists in a combined format as a way to consolidate the amount of widgets.

For that reason I think it would be desirable to provide alternate combined lists for a lot of content that conventionally get partitioned by movies and tv show lists.

- Recently watched items (movies, tv shows)
- In-progress items (movies, tv episodes)
- Watchlist (movies, tv shows)
- Etc

**Comment by jurialmunkey** [comment]
Most of these are simple to do in the code and will have something soon.

Combining movies+tv is easy for these sync lists:
- Recently watched
- Collection
- Favourites
- Watchlist Released (can combine plain watchlist but it runs into the same type of sorting issues, so by released date is better)

Others either don't make much sense (e.g. most watched is pointless due to differences in how "plays" is determined) or are more difficult to achieve because code doesn't already exist for combining movies+episodes (i.e. for in-progress).

**Comment by jurialmunkey** [comment]
Will now be able to use `tmdb_type=both` for these paths:

```
plugin://plugin.video.themoviedb.helper/?info=trakt_history&tmdb_type=both

plugin://plugin.video.themoviedb.helper/?info=trakt_watchlist&tmdb_type=both

plugin://plugin.video.themoviedb.helper/?info=trakt_watchlist_released&tmdb_type=both

plugin://plugin.video.themoviedb.helper/?info=trakt_watchlist_anticipated&tmdb_type=both

plugin://plugin.video.themoviedb.helper/?info=trakt_collection&tmdb_type=both

plugin://plugin.video.themoviedb.helper/?info=trakt_favorites&tmdb_type=both
```
