### ISSUE TITLE
Customize viewtypes error in skin settings

### ISSUE THREAD

**Issue by icpryde** [jurialmunkey/script.skinvariables#6]
When I go into skin settings click on items and views then click on Customize viewtypes I receive an error message not letting me click on it?

I've provided a log file:
https://paste.ubuntu.com/p/c8b3WM9Fp4/

**Comment by jurialmunkey** [comment]
Hey sorry, for some reason I missed the notification of this report. The log is no longer available. Are you still having this error? If so, could you get me a new log

**Comment by dm2912** [comment]
old thread but same issue here.

debug log of trying to do "customize viewtypes" from skin settings (arctic horizon)
[viewtypes.log](https://github.com/jurialmunkey/script.skinvariables/files/5785160/viewtypes.log)

**Comment by jurialmunkey** [comment]
@dm2912 - Thanks for the log. Can you try latest github master version. Should fix the issue.

**Comment by dm2912** [comment]
> @dm2912 - Thanks for the log. Can you try latest github master version. Should fix the issue.

yup. fixed.

**Comment by icpryde** [comment]
@jurialmunkey sorry for the late reply, this update fixed my issue as well. Thank you for fixing it!
