### ISSUE TITLE
strange bug

### ISSUE THREAD

**Issue by Enzoinventor** [jurialmunkey/script.skinvariables#61]
hi, I'm using the fuse skin on my Samsung S24 Ultra mobile phone, I noticed this bug: by enabling the viewing of trailers, everything works fine as long as I'm on WiFi but as soon as I leave the house and use the data connection, it doesn't work anymore. the YouTube APIs are set correctly also because it works under Wify network.  what could it be? at the top right I am shown 2 errors one is playback failed and the second error is variable skin failed. I can't access the log in when on Android 14 the Kodi folder is not accessible. If you know a method to recover the log on Android I'll also post the log file.
 thanks in advance.

**Comment by jurialmunkey** [comment]
Unrelated to script.skinvariables

**Comment by jurialmunkey** [comment]
Need a log to know what the error is. 

But skinvariables does not have anything to do with trailers.

**Comment by Enzoinventor** [comment]
hi, I discovered that it's not the skin's fault but it's actually the YouTube addon that has this bug. I started with a clean installation without skin, I configured the YouTube API and the joke is that when I'm connected via WiFi it works and with the data connection it doesn't show up again. you can close the problem I will investigate in the youtube addon forum to understand what creates this bug. 
Thank you.
