### ISSUE TITLE
[Meta] Submit to Official Repo?

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/script.skinvariables#8]
It seems there have been some inconsistencies with availability, since Matrix changes the way dependencies are served from third-party repositories...

The official repository has version 0.0.3, while this repository is currently at 0.2.5.

**Comment by jurialmunkey** [comment]
FYI - PR Pending:
https://github.com/xbmc/repo-scripts/pull/1913

Once I get SV and TMDbH updated on offical, I'll then submit AH for Matrix.

**Comment by drinfernoo** [comment]
Merged 👌
